### ISSUE TITLE
unable to run the project.

### ISSUE THREAD

**Issue by xain786** [victorkvarghese/react-native-feature-boilerplate#4]
My environment is perfectly set up and I tried to run other projects they are running perfectly fine. Please find the error below.

**error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:**

**Comment by victorkvarghese** [comment]
Fixed with [commit](https://github.com/victorkvarghese/react-native-feature-boilerplate/commit/5bc0a2830f7798473a0a74c0b69cdea172499da4)
