### ISSUE TITLE
Seems outdated and not active project anymore?

### ISSUE THREAD

**Issue by Jayiitb** [victorkvarghese/react-native-feature-boilerplate#5]
Hi @victorkvarghese 
Quite an impressive project this looks to be. 
But seems outdated and not an active project anymore? Do you have any further plans? Can you please update it to `v0.62` RN.

This has the potential of becoming as big as this [masterpiece]( https://github.com/react-boilerplate/react-boilerplate) (25.1K stars)

**Comment by victorkvarghese** [comment]
Hi @Jayiitb 
I got really busy and couldn't update 2 projects simultaneously.  I have updated the project to 0.62.2 with some upgrades over the top. Enjoy!

Fixed with [commit](https://github.com/victorkvarghese/react-native-feature-boilerplate/commit/5bc0a2830f7798473a0a74c0b69cdea172499da4)
