### ISSUE TITLE
Can't Launch the default app in android

### ISSUE THREAD

**Issue by dibakar95** [victorkvarghese/react-native-feature-boilerplate#8]
I did all the steps mentioned but the apps keep crashing in android emulator. I am using Windows OS.

**Comment by victorkvarghese** [comment]
@dibakar95 Can you share more details like screenshot?

**Comment by dibakar95** [comment]
Ok, so after a lot of refactoring I got to know the underlying issue.
I am linking a similar Issue from 2 different github links. Please check it out
[App crashes immediately (Android)](https://github.com/thecodingmachine/react-native-boilerplate/issues/22)
[Discussion: Renaming your React Native App / Project](https://github.com/facebook/react-native/issues/24616)

**Comment by victorkvarghese** [comment]
Might not be related to this boilerplate as I was able to run it both on ios and android

**Comment by victorkvarghese** [comment]
Please make sure you used react native rename properly
